CREATE DATABASE IF NOT EXISTS proyectofinal;
USE proyectofinal;

CREATE TABLE images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE prueba_nula (
  id INT AUTO_INCREMENT PRIMARY KEY,
);